version: '2'
services:
 db:
  container_name: db
  image: mongo:3.4
 schedule-feed:
  depends_on: ["db"]
  container_name: schedule-feed
  build: ./schedule-feed
 feed-rest-api:
  depends_on: ["db", "schedule-feed"]
  container_name: feed-rest-api
  build: ./feed-rest-api
  ports: 
   - 8080:8080